node-image: &node-image
  image: node:12.14.1

build-commands: &build-commands
  commands:
    - npm install
    - npm run lint
    - npm test
    - npm run build

deploy-dev: &deploy-dev
  when:
    event: push
    branch: master

docker-settings: &docker-settings
  image: plugins/docker
  registry: docker.target.com
  username: svcpejkn001
  secrets: [docker_password]

## pipelines, run when particular 'event' conditions are satisfied
pipeline:
  #####################
  ## DEV PIPELINE - builds and packages master
  #####################

  ## install, verify and build our source code
  dev-build-praxis:
    <<: *deploy-dev
    <<: *node-image
    <<: *build-commands
    environment:
      - REACT_APP_ENV=dev

  ## build a docker image for the dev branch/feature
  dev-build-docker-publish:
    <<: *deploy-dev
    <<: *docker-settings
    repo: docker.target.com/app/%%app%%
    tags:
      - 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'

secrets:
  docker_password:
    path: /secret/shared/tap/drone-secrets/ARTIFACTORY_SVCPEJKN001_BINREPO
