stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/npm
    - cache/Cypress

variables:
  NPM_CACHE_DIR: "$CI_PROJECT_DIR/cache/npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

###############################################################################

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install
    
###############################################################################

test:
  image: cypress/browsers:node12.18.0-chrome83-ff77
  script:
    - npm install
    - npx cypress cache path
    - npx cypress cache list
    - npm run cypress:verify
    - NODE_ENV=test npm run test_gitlab
    - npm run coverage
  artifacts:
    when: on_failure
    paths:
      - cypress/videos/*.mp4
      - cypress/screenshots/*.png
    expire_in: 10 days

    when: on_success
    paths:
      - coverage
    expire_in: 60 mins

###############################################################################

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - test
  script:
    - rm -rf public/*
    - cp -r coverage/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days

deploy-nginx:
  image: docker:19.03.11
  stage: deploy
  only:
    - master
  dependencies:
    - build
    - test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - npm run build
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/nginx:latest --tag $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/nginx:latest .
    - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/nginx:latest

###############################################################################
