image: node:latest

include:
  - template: Secret-Detection.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

stages:
  - install
  - build
  - test
  - deploy

cache:
  key: shared-cache
  paths:
    - .npm
    - node_modules/
    - cache/Cypress/

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

services:
  - docker:19.03.11-dind

variables:
  CYPRESS_CACHE_FOLDER: "cache/Cypress/"

###############################################################################

install:
  stage: install
  image: node:latest
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

###############################################################################

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 30 mins

###############################################################################

test:
  stage: test
  image: cypress/browsers:node12.18.0-chrome83-ff77
  script:
    - npm install cypress
    - npm run cypress:verify
    - NODE_ENV=test npm run test_gitlab
    - npm run coverage
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - cypress/videos/
      - cypress/screenshots/
      - coverage/
    reports:
      junit:
        - results/TEST-*.xml

###############################################################################

pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - rm -rf public/*
    - cp -r coverage/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days

###############################################################################

deploy-nginx:
  image: docker:latest
  stage: deploy
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/nginx:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/nginx:latest --tag $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/nginx:latest .
    - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/nginx:latest

###############################################################################
